"""Add owner FK in separate migration

Revision ID: 0741024a61bb
Revises: d87761df646f
Create Date: 2016-07-21 00:42:58.461163

"""

# revision identifiers, used by Alembic.
revision = '0741024a61bb'
down_revision = 'd87761df646f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'server', 'member', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='foreignkey')
    ### end Alembic commands ###
