"""secret column pls

Revision ID: aa3fe8daf971
Revises: b8031705628d
Create Date: 2016-07-24 14:06:04.351031

"""

# revision identifiers, used by Alembic.
revision = 'aa3fe8daf971'
down_revision = 'b8031705628d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_link', sa.Column('secret', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
