"""uhh

Revision ID: f091fd7b28bc
Revises: 8c0c54b11d5c
Create Date: 2016-08-07 19:15:04.914291

"""

# revision identifiers, used by Alembic.
revision = 'f091fd7b28bc'
down_revision = '8c0c54b11d5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'channel_link', 'channel', ['channel_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_link', type_='foreignkey')
    op.drop_table('channel')
    ### end Alembic commands ###
